#!/bin/bash

#-----------
# Configurations
#-----------

GIT_BASE_DIR=${GIT_BASE_DIR-/var/apps}
GIT_REPO_NAME=${GIT_REPO_NAME-samplephp}
GIT_URL=${GIT_URL-https://github.com/aforward/samplephp}
GIT_REMOTE=${GIT_REMOTE-origin}
GIT_BRANCH=${GIT_BRANCH-master}

#-----------
# Install Script
#-----------

if [[ "`which git`" == "" ]]; then
  apt-get install git-core
fi

if [[ ! -e ${GIT_BASE_DIR}/${GIT_REPO_NAME} ]]; then
  (cd ${GIT_BASE_DIR} && git clone ${GIT_URL} ${GIT_REPO_NAME})
else
  (cd ${GIT_BASE_DIR}/${GIT_REPO_NAME} && git checkout ${GIT_BRANCH} && git fetch && git reset --hard ${GIT_REMOTE}/${GIT_BRANCH})
fi


